version: '3.8'
services: 
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/etc/nginx/data
      - ./containers/nginx/templates:/etc/nginx/templates
      - ./containers/nginx/ssl:/etc/letsencrypt/live/localhost
    depends_on: 
      - app
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
      - SERVER=localhost
      - APP=app:3000
      - SSL_CERTIFICATE=local.crt     # production: fullchain.pem 
      - SSL_PRIVATE_KEY=local.key     # production: privkey.pem
  app:
    image: hestelop-app:latest
    expose:
      - 3000
    