version: '3.8'
services: 
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./static
        target: /etc/nginx/data
      - ./containers/nginx/templates:/etc/nginx/templates
      - ./containers/nginx/ssl:/etc/letsencrypt/live/localhost
    depends_on: 
      - app
      - game
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
      - SERVER=localhost
      - APP=app:3000
      - SOCKET=game:3001
      - SSL_CERTIFICATE=local.crt     # production: fullchain.pem 
      - SSL_PRIVATE_KEY=local.key     # production: privkey.pem
  app:
    build:
      context: ./containers/app
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./containers/app/dist/server.js
        target: /usr/src/app/server.js
  game:
    build:
      context: ./containers/game
      dockerfile: Dockerfile
    expose:
      - 3001
    environment:
      - PORT=3001

    