FROM node:12-alpine
ENV NODE_ENV=development
ENV PORT=3000
EXPOSE 3000
WORKDIR /usr/src/app
COPY ./dist .
COPY package*.json ./
RUN npm i --package-lock-only
RUN npm ci --only=prod
CMD ["yarn", "run", "docker"]